sudo: required

services:
  - docker

script:
  - docker-compose run --rm loraserver make test

before_deploy:
  - docker-compose run --rm loraserver make dist

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: dist/upload
    repo: comet-GmbH/comet-GmbH.github.io
    target-branch: master
    keep-history: true
    on:
      tags: true
